/* autogenerated by Processing revision 1307 on 2025-11-06 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class MiniInsaniquarium extends PApplet {


SoundFile suaraPlop;
SoundFile suaraKoin;
SoundFile suaraBeli;
SoundFile bgm;

ArrayList<Ikan> daftarIkan = new ArrayList<Ikan>();
ArrayList<MakananIkan> MakananIkanIkan = new ArrayList<MakananIkan>();
ArrayList<Koin> daftarKoin = new ArrayList<Koin>();

int uang = 100;
int hargaIkan = 50;
int hargaGantiBg = 300; 

PImage bg;
MenuSystem menuScreen; 

int levelMakananIkan = 1;
boolean dekorAktif = false;
int bgIndex = 0;
PImage[] daftarBG;

enum GameState {
  MENU,
  GAMEPLAY,
  HOW_TO_PLAY,
  SETTINGS,
  SHOP,
  CONFIRM_EXIT,
  GAME_OVER 
}

GameState gameState = GameState.MENU;
GameState stateBeforeConfirm;

// Variabel untuk Top Bar
float topBarH = 65; 
float btnBeliX, btnBeliY, btnBeliW, btnBeliH;
float btnGantiBgX, btnGantiBgY, btnGantiBgW, btnGantiBgH;
float btnMenuX, btnMenuY, btnMenuW, btnMenuH;

// Variabel untuk Game Over Screen
float goBtnMainLagiX, goBtnMainLagiY, goBtnMenuX, goBtnMenuY, goBtnW, goBtnH;
int goModalBgColor, goModalBorderColor, goGameOverTextColor, goDescriptionTextColor;
int goBtnMainLagiBg, goBtnMainLagiText, goBtnMenuBg, goBtnMenuText;

// Variabel untuk Confirm Popup
float cfModalX, cfModalY, cfModalW, cfModalH;
float cfBtnYesX, cfBtnYesY, cfBtnNoX, cfBtnNoY, cfBtnW, cfBtnH;
int cfModalBgColor, cfModalBorderColor, cfTitleTextColor, cfDescTextColor;
int cfBtnYesBg, cfBtnYesText, cfBtnNoBg, cfBtnNoText;


// Palet Warna UI Top Bar
int btnBiru, btnKuning, btnMerah, btnDisabled;
int borderCerah, borderHover, borderDisabled;
int textDisabled, textCerah;


public void setup() {
  /* size commented out by preprocessor */;

  try {
    // === BUG FIX DI SINI ===
    daftarBG = new PImage[10]; // Diubah menjadi 4
    daftarBG[0] = loadImage("img/bg1.png");
    daftarBG[1] = loadImage("img/bg2.png");
    daftarBG[2] = loadImage("img/bg3.png");
    daftarBG[3] = loadImage("img/bg4.jpg");
    daftarBG[4] = loadImage("img/bg5.png");
    daftarBG[5] = loadImage("img/bg6.png"); 
    daftarBG[6] = loadImage("img/bg7.png");
    daftarBG[7] = loadImage("img/bg8.png");
    daftarBG[8] = loadImage("img/bg9.jpg");
    daftarBG[9] = loadImage("img/bg10.png");// Diubah menjadi index 3
    bg = daftarBG[0];
  } catch (Exception e) {
    println("Background image not found - using solid color");
    bg = null;
  }

  menuScreen = new MenuSystem(width, height); 

  try {
    suaraPlop = new SoundFile(this, "SE/plop.mp3");
    suaraKoin = new SoundFile(this, "SE/coin.mp3");
    suaraBeli = new SoundFile(this, "SE/purchase.mp3");
    bgm = new SoundFile(this, "SE/bgm_gameplay.mp3");
    bgm.loop();
  } catch (Exception e) {
    println("Audio files not found. Game will run without sound.");
  }

  btnBiru = color(20, 100, 160);
  btnKuning = color(200, 160, 0);
  btnMerah = color(180, 50, 70);
  btnDisabled = color(100, 110, 120, 200);
  
  borderCerah = color(0, 212, 255);
  borderHover = color(255, 255, 255, 200);
  borderDisabled = color(80, 90, 100);
  
  textDisabled = color(180);
  textCerah = color(230);

  // Ukuran Tombol Top Bar
  btnMenuW = 90; 
  btnGantiBgW = 110; 
  btnBeliW = 110; 
  btnMenuH = 40; 
  btnGantiBgH = 40; 
  btnBeliH = 40; 

  // Inisialisasi Palet Warna GAME OVER
  goModalBgColor = color(18, 43, 74); 
  goModalBorderColor = color(101, 214, 173); 
  goGameOverTextColor = color(224, 108, 117); 
  goDescriptionTextColor = color(212, 212, 212); 
  goBtnMainLagiBg = color(101, 214, 173); 
  goBtnMainLagiText = color(30); 
  goBtnMenuBg = color(74, 107, 138); 
  goBtnMenuText = color(230); 

  // Inisialisasi Palet Warna CONFIRM POPUP
  cfModalBgColor = color(18, 43, 74);        
  cfModalBorderColor = color(200, 160, 0);    
  cfTitleTextColor = color(230);              
  cfDescTextColor = color(212);               
  cfBtnYesBg = color(180, 50, 70);            
  cfBtnYesText = color(230);
  cfBtnNoBg = color(74, 107, 138);           
  cfBtnNoText = color(230);

  surface.setResizable(true);
  surface.setLocation(200, 100);
}

public void draw() {
  background(10, 20, 40);

  switch(gameState) {
  case MENU:
    drawMenu();
    break;
  case GAMEPLAY:
    drawGameplay();
    break;
  case HOW_TO_PLAY:
    menuScreen.display();
    menuScreen.drawHowToPlay();
    break;
  case SETTINGS:
    menuScreen.display();
    menuScreen.drawSettings();
    break;
  case CONFIRM_EXIT:
    if (stateBeforeConfirm == GameState.GAMEPLAY) drawGameplay();
    else if (stateBeforeConfirm == GameState.HOW_TO_PLAY) {
      menuScreen.display(); 
      menuScreen.drawHowToPlay();
    } else if (stateBeforeConfirm == GameState.SETTINGS) {
      menuScreen.display(); 
      menuScreen.drawSettings();
    } else if (stateBeforeConfirm == GameState.SHOP) {
      menuScreen.display(); 
      menuScreen.drawShop();
    }
    drawConfirmPopup();
    break;

  case GAME_OVER:
    drawGameplay(); 
    drawGameOverScreen(); 
    break;
  }
}

public void drawMenu() {
  menuScreen.display();
}

public void drawGameplay() {
  lights();

  if (bg != null) image(bg, 0, 0, width, height);
  else background(20, 40, 80);

  if (dekorAktif) {
    drawDekorasiKecil();
  }

  // Draw MakananIkan
  for (int i = MakananIkanIkan.size() - 1; i >= 0; i--) {
    if (i < MakananIkanIkan.size()) {
      MakananIkan m = MakananIkanIkan.get(i);
      m.jatuh(levelMakananIkan);
      m.tampil();
      if (m.pos.y > height) MakananIkanIkan.remove(i);
    }
  }

  // Draw Ikan
  for (int i = daftarIkan.size() - 1; i >= 0; i--) {
    if (i < daftarIkan.size()) {
      Ikan ikan = daftarIkan.get(i);
      ikan.update();
      ikan.tampil();
      ikan.findFood(MakananIkanIkan);
      if (!ikan.isAlive && ikan.alpha <= 0) daftarIkan.remove(i);
    }
  }

  // Draw Koin
  for (int i = daftarKoin.size() - 1; i >= 0; i--) {
    if (i < daftarKoin.size()) {
      Koin k = daftarKoin.get(i);
      k.tampil();
      k.jatuh();
      if (k.pos.y > height) daftarKoin.remove(i);
    }
  }

  hint(DISABLE_DEPTH_TEST);
  perspective();

  drawTopBar(); 

  hint(ENABLE_DEPTH_TEST);

  if (gameState == GameState.GAMEPLAY && daftarIkan.isEmpty() && uang < hargaIkan) {
    gameState = GameState.GAME_OVER;
  }
}

public void drawDekorasiKecil() {
  noStroke();

  float dekorY = topBarH + 20; 

  fill(40, 120, 60, 150);
  ellipse(60, dekorY + 8, 25, 12);
  fill(60, 200, 80, 180);
  rect(56, dekorY - 5, 4, 12);
  rect(64, dekorY - 8, 4, 15);

  fill(40, 120, 60, 150);
  ellipse(width/2, dekorY + 8, 30, 13);
  fill(60, 200, 80, 180);
  rect(width/2 - 12, dekorY - 8, 5, 16);
  rect(width/2, dekorY - 10, 5, 18);
  rect(width/2 + 10, dekorY - 7, 5, 15);

  if (dekorAktif) {
    fill(40, 120, 60, 150);
    ellipse(width - 60, dekorY + 8, 25, 12);
    fill(60, 200, 80, 180);
    rect(width - 65, dekorY - 5, 4, 12);
    rect(width - 57, dekorY - 8, 4, 15);
  }
}

public void drawTopBar() {
  hint(DISABLE_DEPTH_TEST);
  perspective();
  noLights();

  float topBarY = 0;

  fill(10, 31, 63, 220); 
  stroke(borderCerah);
  strokeWeight(2);
  rect(0, topBarY, width, topBarH, 0, 0, 15, 15); 

  noStroke();

  fill(255, 255, 0);
  textSize(32);
  textAlign(LEFT, CENTER);
  text("$" + uang, 20, topBarH / 2 + 5);

  fill(textCerah); 
  textSize(11); 
  textAlign(LEFT, CENTER);
  fill(dekorAktif ? color(100, 255, 100) : color(150));


  btnMenuX = width - btnMenuW - 15;
  btnMenuY = (topBarH - btnMenuH) / 2;

  boolean hoverMenu = (mouseX > btnMenuX && mouseX < btnMenuX + btnMenuW && 
    mouseY > btnMenuY && mouseY < btnMenuY + btnMenuH);

  if (hoverMenu) {
    fill(btnMerah, 240); 
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(btnMerah);
    stroke(btnMerah, 255); 
    strokeWeight(1);
  }
  rect(btnMenuX, btnMenuY, btnMenuW, btnMenuH, 8);

  noStroke();
  fill(255);
  textAlign(CENTER, CENTER);
  textSize(14);
  text("MENU", btnMenuX + btnMenuW / 2, btnMenuY + btnMenuH / 2); 

  btnGantiBgX = btnMenuX - btnGantiBgW - 10;
  btnGantiBgY = (topBarH - btnGantiBgH) / 2;

  boolean hoverGantiBg = (mouseX > btnGantiBgX && mouseX < btnGantiBgX + btnGantiBgW && 
    mouseY > btnGantiBgY && mouseY < btnGantiBgY + btnGantiBgH);
  boolean canGantiBg = (uang >= hargaGantiBg);

  if (!canGantiBg) {
    fill(btnDisabled);
    stroke(borderDisabled);
    strokeWeight(1);
  } else if (hoverGantiBg) {
    fill(btnKuning, 240);
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(btnKuning);
    stroke(btnKuning, 255);
    strokeWeight(1);
  }
  rect(btnGantiBgX, btnGantiBgY, btnGantiBgW, btnGantiBgH, 8);

  noStroke();
  fill(canGantiBg ? 255 : textDisabled); 
  textAlign(CENTER, CENTER);
  textSize(13);
  text("GANTI BG", btnGantiBgX + btnGantiBgW / 2, btnGantiBgY + 12);
  textSize(11);
  fill(canGantiBg ? color(220) : textDisabled); 
  text("(" + hargaGantiBg + "$)", btnGantiBgX + btnGantiBgW / 2, btnGantiBgY + 28);


  btnBeliX = btnGantiBgX - btnBeliW - 10;
  btnBeliY = (topBarH - btnBeliH) / 2;

  boolean hoverBeliIkan = (mouseX > btnBeliX && mouseX < btnBeliX + btnBeliW && 
    mouseY > btnBeliY && mouseY < btnBeliY + btnBeliH);
  boolean canBeliIkan = (uang >= hargaIkan);

  if (!canBeliIkan) {
    fill(btnDisabled);
    stroke(borderDisabled);
    strokeWeight(1);
  } else if (hoverBeliIkan) {
    fill(btnBiru, 240);
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(btnBiru);
    stroke(btnBiru, 255);
    strokeWeight(1);
  }
  rect(btnBeliX, btnBeliY, btnBeliW, btnBeliH, 8);

  noStroke();
  fill(canBeliIkan ? 255 : textDisabled);
  textAlign(CENTER, CENTER);
  textSize(13);
  text("BELI IKAN", btnBeliX + btnBeliW / 2, btnBeliY + 12);
  textSize(11);
  fill(canBeliIkan ? color(220) : textDisabled);
  text("(" + hargaIkan + "$)", btnBeliX + btnBeliW / 2, btnBeliY + 28);


  hint(ENABLE_DEPTH_TEST);
  lights();
}


// =======================================================
// === FUNGSI drawConfirmPopup() DIPERBAIKI TOTAL      ===
// =======================================================
public void drawConfirmPopup() {
  hint(DISABLE_DEPTH_TEST);
  noLights();
  perspective();

  // Latar belakang gelap transparan
  fill(0, 0, 0, 200);
  rect(0, 0, width, height);

  // Kalkulasi Ukuran & Posisi Modal
  cfModalW = width * 0.6f;
  cfModalH = height * 0.4f; // Dibuat sedikit lebih ringkas
  cfModalX = (width - cfModalW) / 2;
  cfModalY = (height - cfModalH) / 2;

  // Latar belakang modal
  fill(cfModalBgColor);
  stroke(cfModalBorderColor);
  strokeWeight(3);
  rect(cfModalX, cfModalY, cfModalW, cfModalH, 20);

  // === Pengaturan Posisi (Y) ===
  float titleY = cfModalY + 50;
  float descY = titleY + 45;
  float buttonY = descY + 60;

  // Teks Judul
  fill(cfTitleTextColor);
  textAlign(CENTER, CENTER);
  textSize(26);
  text("Kembali ke Menu?", width / 2, titleY);

  // Teks Deskripsi
  fill(cfDescTextColor);
  textSize(17);
  text("Anda yakin ingin keluar dari permainan?", width / 2, descY);

  // Pengaturan Tombol
  cfBtnW = (cfModalW / 2) - 70;
  cfBtnH = 45; // Dibuat 45px
  cfBtnYesX = cfModalX + 50; // Padding 50px
  cfBtnYesY = buttonY;
  
  cfBtnNoX = cfModalX + cfModalW - cfBtnW - 50; // Padding 50px
  cfBtnNoY = buttonY;

  // Tombol: YA, KEMBALI (Aksi "Berbahaya")
  boolean hoverYes = (mouseX > cfBtnYesX && mouseX < cfBtnYesX + cfBtnW && 
    mouseY > cfBtnYesY && mouseY < cfBtnYesY + cfBtnH);

  if (hoverYes) {
    fill(cfBtnYesBg, 220); 
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(cfBtnYesBg);
    noStroke();
  }
  rect(cfBtnYesX, cfBtnYesY, cfBtnW, cfBtnH, 12);
  fill(cfBtnYesText);
  textSize(16);
  text("YA, KEMBALI", cfBtnYesX + cfBtnW / 2, cfBtnYesY + cfBtnH / 2);

  // Tombol: TIDAK, BATAL (Aksi "Aman")
  boolean hoverNo = (mouseX > cfBtnNoX && mouseX < cfBtnNoX + cfBtnW && 
    mouseY > cfBtnNoY && mouseY < cfBtnNoY + cfBtnH);

  if (hoverNo) {
    fill(cfBtnNoBg, 220); 
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(cfBtnNoBg);
    noStroke();
  }
  rect(cfBtnNoX, cfBtnNoY, cfBtnW, cfBtnH, 12);
  fill(cfBtnNoText);
  text("TIDAK, BATAL", cfBtnNoX + cfBtnW / 2, cfBtnNoY + cfBtnH / 2);

  hint(ENABLE_DEPTH_TEST);
}

public void drawGameOverScreen() {
  hint(DISABLE_DEPTH_TEST);
  noLights();
  perspective();

  fill(0, 0, 0, 200); 
  rect(0, 0, width, height);

  float modalWidth = width * 0.7f;
  float modalHeight = height * 0.45f;
  float modalX = (width - modalWidth) / 2;
  float modalY = (height - modalHeight) / 2;

  // Latar belakang modal
  fill(goModalBgColor);
  stroke(goModalBorderColor); 
  strokeWeight(3);
  rect(modalX, modalY, modalWidth, modalHeight, 20);
  float paddingAtas = 60; // Jarak dari atas modal ke judul
  float spasiAntarElemen = 60; // Jarak antar elemen (Judul -> Deskripsi -> Tombol)

  goBtnH = 50; 
  float titleY = modalY + paddingAtas;
  float descY = titleY + spasiAntarElemen;
  float buttonY = descY + spasiAntarElemen; // Tombol akan *dimulai* dari posisi ini

  fill(goGameOverTextColor);
  textAlign(CENTER, CENTER); 
  textSize(36);
  text("GAME OVER", width / 2, titleY);


  fill(goDescriptionTextColor);
  textAlign(CENTER, CENTER); 
  textSize(18);
  text("Semua ikanmu telah tiada...", width / 2, descY);

  goBtnW = (modalWidth / 2) - 70;
  goBtnMainLagiX = modalX + 50; 
  goBtnMainLagiY = buttonY; 
  
  goBtnMenuX = modalX + modalWidth - goBtnW - 50; 
  goBtnMenuY = buttonY; 

  boolean hoverMainLagi = (mouseX > goBtnMainLagiX && mouseX < goBtnMainLagiX + goBtnW && 
    mouseY > goBtnMainLagiY && mouseY < goBtnMainLagiY + goBtnH);

  if (hoverMainLagi) {
    fill(goBtnMainLagiBg, 220); 
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(goBtnMainLagiBg);
    noStroke(); 
  }
  rect(goBtnMainLagiX, goBtnMainLagiY, goBtnW, goBtnH, 12); 
  fill(goBtnMainLagiText);
  textSize(16);
  textAlign(CENTER, CENTER);
  text("MAIN LAGI", goBtnMainLagiX + goBtnW / 2, goBtnMainLagiY + goBtnH / 2);
  boolean hoverMenuUtama = (mouseX > goBtnMenuX && mouseX < goBtnMenuX + goBtnW && 
    mouseY > goBtnMenuY && mouseY < goBtnMenuY + goBtnH);

  if (hoverMenuUtama) {
    fill(goBtnMenuBg, 220); 
    stroke(borderHover);
    strokeWeight(2);
  } else {
    fill(goBtnMenuBg);
    noStroke(); 
  }
  rect(goBtnMenuX, goBtnMenuY, goBtnW, goBtnH, 12); 
  fill(goBtnMenuText);
  textAlign(CENTER, CENTER); // Pastikan Text Align untuk tombol
  text("MENU UTAMA", goBtnMenuX + goBtnW / 2, goBtnMenuY + goBtnH / 2);

  hint(ENABLE_DEPTH_TEST);
}


public void mousePressed() {
  if (gameState == GameState.MENU) {
    int buttonClicked = menuScreen.checkButtonClick(mouseX, mouseY);
    if (buttonClicked == 1) { // MULAI
      gameState = GameState.GAMEPLAY;
      uang = 500; // Mulai dengan uang 500
      daftarIkan.clear();
      MakananIkanIkan.clear();
      daftarKoin.clear();
      dekorAktif = false;
      levelMakananIkan = 1;
    } else if (buttonClicked == 2) gameState = GameState.HOW_TO_PLAY;
    else if (buttonClicked == 3) gameState = GameState.SETTINGS;
    else if (buttonClicked == 4) gameState = GameState.SHOP;
    else if (buttonClicked == 5) exit();
    return;
  }

  if (gameState == GameState.HOW_TO_PLAY) {
    if (menuScreen.checkBackButton(mouseX, mouseY)) gameState = GameState.MENU;
    return;
  }

  if (gameState == GameState.SETTINGS) {
    if (menuScreen.checkMuteButton(mouseX, mouseY)) {
      menuScreen.toggleMute();
      return;
    }
    if (menuScreen.checkBackButton(mouseX, mouseY)) gameState = GameState.MENU;
    return;
  }

  if (gameState == GameState.SHOP) {
    int itemClicked = menuScreen.checkShopItemClick(mouseX, mouseY);

    if (itemClicked == 1) {
      if (uang >= 100) {
        uang -= 100;
        levelMakananIkan++;
        if (suaraBeli != null) suaraBeli.play();
      }
    } else if (itemClicked == 2) {
      if (uang >= 200) {
        uang -= 200;
        dekorAktif = true;
        if (suaraBeli != null) suaraBeli.play();
      }
    } else if (itemClicked == 3) {
      if (uang >= hargaGantiBg) { 
        uang -= hargaGantiBg;
        bgIndex = (bgIndex + 1) % daftarBG.length;
        if (daftarBG != null && bgIndex < daftarBG.length) {
          bg = daftarBG[bgIndex];
        }
        if (suaraBeli != null) suaraBeli.play();
      }
    }

    if (menuScreen.checkBackButton(mouseX, mouseY)) gameState = GameState.MENU;
    return;
  }
  if (gameState == GameState.CONFIRM_EXIT) {
    if (mouseX > cfBtnYesX && mouseX < cfBtnYesX + cfBtnW && 
      mouseY > cfBtnYesY && mouseY < cfBtnYesY + cfBtnH) {
      gameState = GameState.MENU;
      return;
    }
    if (mouseX > cfBtnNoX && mouseX < cfBtnNoX + cfBtnW && 
      mouseY > cfBtnNoY && mouseY < cfBtnNoY + cfBtnH) {
      gameState = stateBeforeConfirm;
      return;
    }
  }

  if (gameState == GameState.GAME_OVER) {
    if (mouseX > goBtnMainLagiX && mouseX < goBtnMainLagiX + goBtnW && 
      mouseY > goBtnMainLagiY && mouseY < goBtnMainLagiY + goBtnH) {
      uang = 500; // Mulai lagi dengan uang 500
      daftarIkan.clear();
      MakananIkanIkan.clear();
      daftarKoin.clear();
      dekorAktif = false;
      levelMakananIkan = 1;
      gameState = GameState.GAMEPLAY;
      return;
    }
    if (mouseX > goBtnMenuX && mouseX < goBtnMenuX + goBtnW && 
      mouseY > goBtnMenuY && mouseY < goBtnMenuY + goBtnH) {
      gameState = GameState.MENU;
      return;
    }
    return; 
  }

  if (gameState == GameState.GAMEPLAY) {
    if (mouseX > btnMenuX && mouseX < btnMenuX + btnMenuW && 
      mouseY > btnMenuY && mouseY < btnMenuY + btnMenuH) {
      stateBeforeConfirm = GameState.GAMEPLAY;
      gameState = GameState.CONFIRM_EXIT;
      return;
    }
    if (mouseX > btnBeliX && mouseX < btnBeliX + btnBeliW && 
      mouseY > btnBeliY && mouseY < btnBeliY + btnBeliH) {
      if (uang >= hargaIkan) { 
        uang -= hargaIkan;
        daftarIkan.add(new Ikan(random(100, width-100), random(topBarH + 50, height-100))); 
        if (suaraBeli != null) suaraBeli.play();
      }
      return;
    }
    if (mouseX > btnGantiBgX && mouseX < btnGantiBgX + btnGantiBgW && 
      mouseY > btnGantiBgY && mouseY < btnGantiBgY + btnGantiBgH) {
      if (uang >= hargaGantiBg) { 
        uang -= hargaGantiBg;
        bgIndex = (bgIndex + 1) % daftarBG.length;
        if (daftarBG != null && bgIndex < daftarBG.length) {
          bg = daftarBG[bgIndex];
        }
        if (suaraBeli != null) suaraBeli.play();
      }
      return;
    }
    for (int i = daftarKoin.size() - 1; i >= 0; i--) {
      if (i < daftarKoin.size()) {
        Koin k = daftarKoin.get(i);
        if (dist(mouseX, mouseY, k.pos.x, k.pos.y) < k.ukuran / 2) {
          uang += k.nilai;
          daftarKoin.remove(i);
          if (suaraKoin != null) suaraKoin.play();
          return;
        }
      }
    }
    if (mouseY > topBarH) { 
      MakananIkanIkan.add(new MakananIkan(mouseX, mouseY));
      if (suaraPlop != null) suaraPlop.play();
    }
  }
}
class Ikan {
  PVector pos;
  PVector vel;
  PVector targetPos;
  float hunger;
  float ukuran;
  boolean isAlive;
  float alpha;
  int makanCount;
  int makanThreshold = 5;
  float ukuranMax = 50;
  boolean useBezier;

  int warnaDasar;
  int warnaEkor;

  Ikan(float x, float y) {
    pos = new PVector(x, y);
    vel = new PVector(0, 0);
    hunger = 50;
    ukuran = 20;
    isAlive = true;
    alpha = 255;
    makanCount = 0;
    useBezier = random(1) < 0.5f;

    warnaDasar = color(random(80, 255), random(80, 255), random(80, 255));
    warnaEkor = color(random(80, 255), random(80, 255), random(80, 255));

    setNewRandomTarget();
  }

  public void setNewRandomTarget() {
    targetPos = new PVector(random(width), random(height));
  }

  public void findFood(ArrayList<MakananIkan> foods) {
    if (!isAlive) return;

    if (hunger < 50 || foods.isEmpty()) {
      if (pos.dist(targetPos) < 15) {
        setNewRandomTarget();
      }
      return;
    }

    MakananIkan closestFood = foods.get(0);
    float minDistance = pos.dist(closestFood.pos);

    for (MakananIkan f : foods) {
      float d = pos.dist(f.pos);
      if (d < minDistance) {
        minDistance = d;
        closestFood = f;
      }
    }

    targetPos = closestFood.pos.copy();

    if (minDistance < ukuran / 2) {
      eat(foods, closestFood);
    }
  }

  public void eat(ArrayList<MakananIkan> foods, MakananIkan f) {
  if (!isAlive) return;
  foods.remove(f);
  hunger = 0;
  jatuhkanKoin();
  setNewRandomTarget();
  makanCount++;
  if (makanCount >= makanThreshold && ukuran < ukuranMax) {
    ukuran += 10;
    makanCount = 0;
  }
}

  public void jatuhkanKoin() {
    daftarKoin.add(new Koin(pos.x, pos.y, 10));
  }

  public void update() {
    if (!isAlive) {
      alpha -= 2;
      alpha = max(alpha, 0);
      return;
    }

    if (hunger >= 100) {
      isAlive = false;
      return;
    }

    float speed = 1.5f;
    PVector arah = PVector.sub(targetPos, pos);

    if (arah.mag() < speed) {
      pos = targetPos.copy();
      vel.set(0, 0);
    } else {
      arah.normalize();
      arah.mult(speed);
      vel = arah.copy();
      pos.add(vel);
    }

    hunger += 0.05f;
    hunger = constrain(hunger, 0, 100);
  }

  public void tampil() {
    if (alpha <= 0) return;
    pushMatrix();
    translate(pos.x, pos.y);

    float angle = atan2(vel.y, vel.x);
    rotate(angle);
    noStroke();

    int tubuh = lerpColor(warnaDasar, color(255, 0, 0), hunger / 100.0f);
    fill(tubuh, alpha);
    if (useBezier) {
      beginShape();
      vertex(-ukuran/2, 0);
      bezierVertex(-ukuran/4, -ukuran/3, ukuran/4, -ukuran/3, ukuran/2, 0);
      bezierVertex(ukuran/4, ukuran/3, -ukuran/4, ukuran/3, -ukuran/2, 0);
      endShape(CLOSE);
    } else {
      ellipse(0, 0, ukuran, ukuran * 0.7f);
    }

    fill(lerpColor(warnaEkor, color(255, 200, 200), hunger / 120.0f), alpha);
    if (useBezier) {
      beginShape();
      vertex(-ukuran/2, 0);
      bezierVertex(-ukuran, -ukuran/4, -ukuran * 1.2f, 0, -ukuran, ukuran/4);
      endShape();
    } else {
      triangle(-ukuran/2, 0, -ukuran, -ukuran/3, -ukuran, ukuran/3);
    }

    if (isAlive) {
      fill(0, alpha);
      ellipse(ukuran/4, -ukuran/8, 3, 3);
    } else {
      stroke(0, alpha);
      strokeWeight(1);
      line(ukuran/4 - 1.5f, -ukuran/8 - 1.5f, ukuran/4 + 1.5f, -ukuran/8 + 1.5f);
      line(ukuran/4 + 1.5f, -ukuran/8 - 1.5f, ukuran/4 - 1.5f, -ukuran/8 + 1.5f);
      noStroke();
    }

    popMatrix();
  }
}

class Koin {

  PVector pos;
  PVector vel;
  int nilai;
  float ukuran = 30;
  float sudutPutar = 0; 

  Koin(float x, float y, int n) {
    pos = new PVector(x, y);
    vel = new PVector(0, 1.0f); 
    nilai = n;
  }

  public void tampil() {
    pushMatrix();
    translate(pos.x, pos.y);
    rotate(sudutPutar);
    stroke(255, 200, 0);
    strokeWeight(3);
    fill(255, 220, 0); // Kuning
    ellipse(0, 0, ukuran, ukuran);
    fill(200, 150, 0);
    textAlign(CENTER, CENTER);
    textSize(18);
    text("$", 0, 0);
    popMatrix();
  }

  public void jatuh() {
    pos.add(vel);
    sudutPutar += 0.1f; 
  }
}
class MakananIkan {
  PVector pos;       
  float kecepatan;   
  float ukuran;      
  int warna;       
  MakananIkan(float x, float y) {
    pos = new PVector(x, y);
    kecepatan = random(1.5f, 2.5f);  
    ukuran = 10;
    warna = color(255, 220, 100);
  }

  public void jatuh(int levelMakananIkan) {
    pos.y += kecepatan * (1 + (levelMakananIkan - 1) * 0.3f);
  }
  public void tampil() {
    noStroke();
    fill(warna);
    ellipse(pos.x, pos.y, ukuran, ukuran);
  }
}
class MenuSystem {
  int screenWidth, screenHeight;
  ArrayList<Menu3DButton> buttons;
  ArrayList<Bubble3D> bubbles;
  float glowAmount = 0;
  float backBtnX, backBtnY, backBtnW = 120, backBtnH = 40;
  float muteBtnX, muteBtnY, muteBtnW = 200, muteBtnH = 50;

  boolean isMuted = false;
  
  PImage logo;

  MenuSystem(int w, int h) {
    screenWidth = w;
    screenHeight = h;
    initializeButtons();
    initializeBubbles();
    
    try {
      logo = loadImage("img/Logo.png");
    } catch (Exception e) {
      println("Gagal memuat file img/Logo.png");
      logo = null;
    }
  }

  public void initializeButtons() {
    buttons = new ArrayList<Menu3DButton>();
   int centerX = screenWidth / 2;
  
   int centerY = screenHeight / 2 + (int)(screenHeight * 0.15f); // Aslinya: screenHeight / 2
  
    int buttonWidth = (int)(screenWidth * 0.22f);
    int buttonHeight = (int)(screenHeight * 0.065f);
    int verticalSpacing = (int)(screenHeight * 0.055f);
  
    String[] labels = { "MULAI", "CARA BERMAIN", "PENGATURAN", "KELUAR" };
    int[] colors = {
      color(0, 212, 255),
      color(255, 215, 0),
      color(160, 160, 160),
      color(102, 255, 204),
      color(255, 107, 107)
    };
    
    int totalHeight = labels.length * buttonHeight + (labels.length - 1) * verticalSpacing;
    int startY = centerY - totalHeight / 2 + (int)(screenHeight * 0.05f);
    
    for (int i = 0; i < labels.length; i++) {
      int y = startY + i * (buttonHeight + verticalSpacing);
      buttons.add(new Menu3DButton(
        centerX - buttonWidth / 2,
        y,
        buttonWidth,
        buttonHeight,
        labels[i],
        colors[i],
        i + 1
        ));
    }
  }

  public void initializeBubbles() {
    bubbles = new ArrayList<Bubble3D>();
    for (int i = 0; i < 20; i++) {
      bubbles.add(new Bubble3D(random(screenWidth), random(screenHeight), random(10, 40), screenWidth, screenHeight));
    }
  }

  public void display() {
    updateScreenSize();
    initializeButtons();
    perspective();
    lights();
    drawGradientBackground();

    for (Bubble3D bubble : bubbles) {
      bubble.update();
      bubble.display();
    }
    
    drawLogo();
    drawTitle();

    for (Menu3DButton btn : buttons) {
      btn.update(mouseX, mouseY);
      btn.display();
    }

    drawFooter();
  }
  public void updateScreenSize() {
  screenWidth = width;
  screenHeight = height;
}


  public void drawGradientBackground() {
    hint(DISABLE_DEPTH_TEST);
    noLights();

    for (int y = 0; y < screenHeight; y++) {
      float inter = map(y, 0, screenHeight, 0, 1);
      int topColor = color(10, 31, 63);
      int midColor = color(26, 77, 122);
      int botColor = color(13, 59, 102);
      int c = inter < 0.5f ? lerpColor(topColor, midColor, inter * 2) : lerpColor(midColor, botColor, (inter - 0.5f) * 2);
      stroke(c);
      line(0, y, screenWidth, y);
    }

    hint(ENABLE_DEPTH_TEST);
    lights();
  }

  public void drawTitle() {
    hint(DISABLE_DEPTH_TEST);
    glowAmount = sin(frameCount * 0.02f) * 0.5f + 0.5f;
  
    float titleSize = screenHeight * 0.12f;
    float subtitleSize = screenHeight * 0.04f;
  
    fill(0, 255, 200);
    textAlign(CENTER);
    textSize((int)titleSize);
  
    float titleY = screenHeight * 0.30f;
    float subtitleY = screenHeight * 0.37f; // Sub-judul sedikit di bawahnya
  
    for (int i = 0; i < 3; i++) {
      float alpha = 100 * (1 - i * 0.3f) * glowAmount;
      fill(0, 255, 200, alpha);
      text("MINI INSANIQUARIUM", screenWidth / 2, titleY - i * 5); // Terapkan titleY
    }
  
    fill(255);
    text("MINI INSANIQUARIUM", screenWidth / 2, titleY); // Terapkan titleY
    textSize((int)subtitleSize);
    fill(160, 230, 229);
    text("~ Simulasikan Akuarium mu ~", screenWidth / 2, subtitleY); // Terapkan subtitleY
  
    hint(ENABLE_DEPTH_TEST);
  }
  
  public void drawLogo() {
    if (logo == null) {
      return; 
    }

   hint(DISABLE_DEPTH_TEST);
    noLights();

    pushMatrix();
    
    imageMode(CENTER);
    float logoWidth = 250;
    float logoHeight = logo.height * (logoWidth / logo.width); // Menjaga rasio aspek

    float logoY = screenHeight * 0.15f;
   image(logo, screenWidth / 2, logoY, logoWidth, logoHeight);
    imageMode(CORNER); 
    popMatrix();
    hint(ENABLE_DEPTH_TEST);
    lights();
  }

  public void drawFooter() {
    hint(DISABLE_DEPTH_TEST);
    fill(255, 255, 255, 150);
    textSize(12);
    textAlign(RIGHT);
    text("Dibuat dengan Processing", screenWidth - 20, screenHeight - 20);
    text("Mini Insaniquarium v1.0", screenWidth - 20, screenHeight - 5);
    hint(ENABLE_DEPTH_TEST);
  }

  public int checkButtonClick(float mx, float my) {
    for (Menu3DButton btn : buttons) {
      if (btn.isClicked(mx, my)) {
        return btn.id;
      }
    }
    return 0;
  }

  public void drawHowToPlay() {
    hint(DISABLE_DEPTH_TEST);
    fill(0, 0, 0, 150);
    rect(0, 0, screenWidth, screenHeight);

    float modalWidth = screenWidth * 0.85f;
    float modalHeight = screenHeight * 0.85f;
    float modalX = (screenWidth - modalWidth) / 2;
    float modalY = (screenHeight - modalHeight) / 2;

    fill(10, 31, 63);
    stroke(0, 212, 255);
    strokeWeight(3);
    rect(modalX, modalY, modalWidth, modalHeight, 20);

    fill(0, 212, 255);
    textAlign(CENTER);
    textSize((int)(screenHeight * 0.06f));
    text("CARA BERMAIN", screenWidth / 2, modalY + 50);

    fill(224, 224, 224);
    textSize((int)(screenHeight * 0.03f));
    textAlign(LEFT);

    float textX = modalX + 40;
    float textY = modalY + 110;
    float lineH = screenHeight * 0.045f;

    text("TUJUAN PERMAINAN:", textX, textY);
    textY += lineH;
    text("Beli ikan, beri mereka makan, dan kumpulkan koin!", textX, textY);
    textY += lineH * 1.5f;

    text("LANGKAH BERMAIN:", textX, textY);
    textY += lineH;
    text("1. Klik tombol 'Beli Ikan' untuk membeli ikan (harga 50 koin)", textX, textY);
    textY += lineH;
    text("2. Klik di mana saja di akuarium untuk memberi makan", textX, textY);
    textY += lineH;
    text("3. Ikan akan makan otomatis saat lapar", textX, textY);
    textY += lineH;
    text("4. Ambil koin yang dijatuhkan ikan untuk mendapat uang", textX, textY);
    textY += lineH;
    text("5. Ikan tumbuh besar setelah makan 5 kali!", textX, textY);

    drawBackButton(modalY + modalHeight);

    hint(ENABLE_DEPTH_TEST);
  }

  public void drawSettings() {
    drawModal("PENGATURAN", 
      new String[]{
        "Suara: " + (isMuted ? "Nonaktif" : "Aktif"),
        "Kualitas: Tinggi",
        "Kesulitan: Normal"
      });

    muteBtnX = screenWidth / 2 - muteBtnW / 2;
    muteBtnY = screenHeight / 2 + 100;
    fill(isMuted ? color(255, 107, 107) : color(100, 200, 100));
    rect(muteBtnX, muteBtnY, muteBtnW, muteBtnH, 10);
    fill(255);
    textAlign(CENTER, CENTER);
    textSize(20);
    text(isMuted ? "Unmute Musik" : "Mute Musik", screenWidth / 2, muteBtnY + muteBtnH / 2);

    drawBackButton(screenHeight * 0.9f);
  }

  public void drawShop() {
    hint(DISABLE_DEPTH_TEST);
    fill(0, 0, 0, 150);
    rect(0, 0, screenWidth, screenHeight);

    float modalWidth = screenWidth * 0.9f;
    float modalHeight = screenHeight * 0.9f;
    float modalX = (screenWidth - modalWidth) / 2;
    float modalY = (screenHeight - modalHeight) / 2;

    fill(10, 31, 63);
    stroke(102, 255, 204);
    strokeWeight(3);
    rect(modalX, modalY, modalWidth, modalHeight, 20);

    fill(102, 255, 204);
    textAlign(CENTER);
    textSize((int)(screenHeight * 0.07f));
    text("TOKO UPGRADE", screenWidth / 2, modalY + 50);

    float leftPanelX = modalX + 30;
    float leftPanelY = modalY + 100;
    float leftPanelW = modalWidth * 0.45f;
    float leftPanelH = modalHeight - 150;

    float rightPanelX = leftPanelX + leftPanelW + 30;
    float rightPanelY = leftPanelY;
    float rightPanelW = modalWidth * 0.45f;
    float rightPanelH = modalHeight - 150;

    // LEFT PANEL: PREVIEW
    fill(30, 60, 90);
    stroke(0, 212, 255);
    strokeWeight(2);
    rect(leftPanelX, leftPanelY, leftPanelW, leftPanelH, 10);

    fill(0, 212, 255);
    textAlign(CENTER);
    textSize((int)(screenHeight * 0.04f));
    text("PREVIEW", leftPanelX + leftPanelW / 2, leftPanelY + 25);

    float previewW = leftPanelW - 30;
    float previewH = leftPanelH - 80;
    float previewX = leftPanelX + 15;
    float previewY = leftPanelY + 50;

    fill(20, 40, 80);
    stroke(0, 150, 180);
    strokeWeight(1);
    rect(previewX, previewY, previewW, previewH, 5);

    if (daftarBG != null && bgIndex < daftarBG.length && daftarBG[bgIndex] != null) {
      image(daftarBG[bgIndex], previewX, previewY, previewW, previewH);
    }

    fill(255);
    textAlign(CENTER);
    textSize((int)(screenHeight * 0.025f));
    text("Background #" + (bgIndex + 1), leftPanelX + leftPanelW / 2, previewY + previewH + 25);

    // RIGHT PANEL: ITEMS
    fill(224, 224, 224);
    textSize((int)(screenHeight * 0.03f));
    textAlign(LEFT);

    float itemX = rightPanelX + 15;
    float itemY = rightPanelY + 30;
    float itemSpacing = (rightPanelH - 50) / 3;

    drawShopItem(itemX, itemY, rightPanelW - 30, 50, 
      "UPGRADE MakananIkan", "Lv. " + levelMakananIkan, "100 $");

    drawShopItem(itemX, itemY + itemSpacing, rightPanelW - 30, 50, 
      "BELI DEKORASI", "Tambah Tanaman", "200 $");

    drawShopItem(itemX, itemY + itemSpacing * 2, rightPanelW - 30, 50, 
      "GANTI BACKGROUND", "Next BG", "300 $");

    drawBackButton(modalY + modalHeight);

    hint(ENABLE_DEPTH_TEST);
  }

  public void drawShopItem(float x, float y, float w, float h, String title, String desc, String price) {
    fill(40, 80, 120);
    stroke(102, 255, 204);
    strokeWeight(2);
    rect(x, y, w, h, 8);

    if (mouseX > x && mouseX < x + w && mouseY > y && mouseY < y + h) {
      fill(60, 120, 160, 100);
      rect(x, y, w, h, 8);
    }

    fill(102, 255, 204);
    textAlign(LEFT);
    textSize(14);
    text(title, x + 15, y + 20);

    fill(200, 200, 200);
    textSize(12);
    text(desc, x + 15, y + 35);

    fill(255, 220, 100);
    textAlign(RIGHT);
    textSize(13);
    text(price, x + w - 15, y + 22);
  }

  public void drawModal(String title, String[] lines) {
    hint(DISABLE_DEPTH_TEST);
    fill(0, 0, 0, 150);
    rect(0, 0, screenWidth, screenHeight);

    float modalWidth = screenWidth * 0.8f;
    float modalHeight = screenHeight * 0.75f;
    float modalX = (screenWidth - modalWidth) / 2;
    float modalY = (screenHeight - modalHeight) / 2;

    fill(10, 31, 63);
    stroke(0, 212, 255);
    strokeWeight(3);
    rect(modalX, modalY, modalWidth, modalHeight, 20);

    fill(0, 212, 255);
    textAlign(CENTER);
    textSize((int)(screenHeight * 0.06f));
    text(title, screenWidth / 2, modalY + 50);

    fill(224, 224, 224);
    textSize((int)(screenHeight * 0.03f));
    textAlign(LEFT);

    float textX = modalX + 40;
    float textY = modalY + 120;
    float lineH = screenHeight * 0.045f;

    for (String line : lines) {
      text(line, textX, textY);
      textY += lineH;
    }

    hint(ENABLE_DEPTH_TEST);
  }

  public void toggleMute() {
    isMuted = !isMuted;
    if (isMuted) {
      if (bgm != null && bgm.isPlaying()) bgm.stop();
    } else {
      if (bgm != null && !bgm.isPlaying()) bgm.loop();
    }
  }

  public boolean checkMuteButton(float mx, float my) {
    return (mx > muteBtnX && mx < muteBtnX + muteBtnW && my > muteBtnY && my < muteBtnY + muteBtnH);
  }

  public void drawBackButton(float modalBottomY) {
    backBtnW = 140;
    backBtnH = 45;
    backBtnX = screenWidth / 2 - backBtnW / 2;
    backBtnY = modalBottomY - backBtnH - 20;

    fill(255, 107, 107);
    stroke(255);
    strokeWeight(2);
    rect(backBtnX, backBtnY, backBtnW, backBtnH, 12);

    fill(255);
    textAlign(CENTER, CENTER);
    textSize(18);
    text("KEMBALI", backBtnX + backBtnW / 2, backBtnY + backBtnH / 2);
  }

  public boolean checkBackButton(float mx, float my) {
    return (mx > backBtnX && mx < backBtnX + backBtnW && my > backBtnY && my < backBtnY + backBtnH);
  }

  public int checkShopItemClick(float mx, float my) {
    float modalWidth = screenWidth * 0.9f;
    float modalHeight = screenHeight * 0.9f;
    float modalX = (screenWidth - modalWidth) / 2;
    float modalY = (screenHeight - modalHeight) / 2;

    float leftPanelW = modalWidth * 0.45f;
    float rightPanelX = modalX + 30 + leftPanelW + 30;
    float rightPanelY = modalY + 100;
    float rightPanelW = modalWidth * 0.45f;
    float rightPanelH = modalHeight - 150;

    float itemX = rightPanelX + 15;
    float itemY = rightPanelY + 30;
    float itemSpacing = (rightPanelH - 50) / 3;
    float itemW = rightPanelW - 30;
    float itemH = 50;

    if (mx > itemX && mx < itemX + itemW && my > itemY && my < itemY + itemH) return 1;
    if (mx > itemX && mx < itemX + itemW && my > itemY + itemSpacing && my < itemY + itemSpacing + itemH) return 2;
    if (mx > itemX && mx < itemX + itemW && my > itemY + itemSpacing * 2 && my < itemY + itemSpacing * 2 + itemH) return 3;

    return 0;
  }
}
class Bubble3D {
  float x, y, size, speedY, wobble;
  int screenWidth, screenHeight;

  Bubble3D(float x, float y, float s, int w, int h) {
    this.x = x;
    this.y = y;
    this.size = s;
    this.speedY = random(0.5f, 2);
    this.wobble = random(TWO_PI);
    this.screenWidth = w;
    this.screenHeight = h;
  }

  public void update() {
    y -= speedY;
    wobble += 0.05f;
    x += sin(wobble) * 0.5f;

    if (y < -50) {
      y = screenHeight + 50;
      x = random(screenWidth);
    }
  }

  public void display() {
    pushMatrix();
    translate(x, y, 0);
    noStroke();
    fill(255, 255, 255, 60);
    sphere(size);
    fill(255, 255, 255, 100);
    pushMatrix();
    translate(-size / 3, -size / 3, size / 2);
    sphere(size / 4);
    popMatrix();
    popMatrix();
  }
}

class Menu3DButton {
  float x, y, w, h;
  String label;
  int baseColor;
  int id;
  boolean isHovered;
  float hoverAmount;

  Menu3DButton(float x, float y, float w, float h, String label, int c, int id) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.label = label;
    this.baseColor = c;
    this.id = id;
    this.isHovered = false;
    this.hoverAmount = 0;
  }

  public void update(float mx, float my) {
    isHovered = (mx > x && mx < x + w && my > y && my < y + h);
    hoverAmount = constrain(hoverAmount + (isHovered ? 0.1f : -0.1f), 0, 1);
  }

  public void display() {
    hint(DISABLE_DEPTH_TEST);
    float scale = 1 + hoverAmount * 0.1f;
    float scaledW = w * scale;
    float scaledH = h * scale;
    float offsetX = x + (w - scaledW) / 2;
    float offsetY = y + (h - scaledH) / 2;

    fill(0, 0, 0, 100);
    rect(offsetX + 5, offsetY + 5, scaledW, scaledH, 15);

    fill(baseColor);
    stroke(255, 255, 255, 150 + hoverAmount * 105);
    strokeWeight(3 + hoverAmount * 2);
    rect(offsetX, offsetY, scaledW, scaledH, 15);

    if (isHovered) {
      noFill();
      stroke(255, 255, 255, 100 * hoverAmount);
      strokeWeight(2);
      rect(offsetX - 5, offsetY - 5, scaledW + 10, scaledH + 10, 15);
    }

    fill(255);
    textAlign(CENTER, CENTER);
    textSize(16 + hoverAmount * 2);
    text(label, offsetX + scaledW / 2, offsetY + scaledH / 2);

    hint(ENABLE_DEPTH_TEST);
  }

  public boolean isClicked(float mx, float my) {
    return (mx > x && mx < x + w && my > y && my < y + h);
  }
}

class Tombol {
  float x, y, w, h;
  String label;
  Tombol(float x, float y, float w, float h, String label) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.label = label;
  }

  public void tampil() {
    stroke(255);
    strokeWeight(2);
    if (isDiKlik(mouseX, mouseY)) {
      fill(100, 200, 100); 
    } else {
      fill(50, 150, 50); 
    }
    rect(x, y, w, h, 10); 
    
    // Teks
    fill(255);
    textAlign(CENTER, CENTER);
    textSize(16);
    text(label, x + w/2, y + h/2);
  }
  public boolean isDiKlik(float mx, float my) {
    return (mx > x && mx < x + w && my > y && my < y + h);
  }
}


  public void settings() { size(800, 600, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "MiniInsaniquarium" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
